### ISSUE TITLE
BGE Profile epic - Develop BGE RO-Crate profile

### ISSUE THREAD

**Issue by elichad** [eScienceLab/RO-Crate_Issues#94]
https://docs.google.com/document/d/1c_F5Bcuu7ZUED3F_Z0yDVBwlCqrzMMynh-KOCZq4kbQ/edit?tab=t.0#heading=h.imojq1adyfaf

Steps:
- [x] #95
- [x] Roughly draft the RO-Crate structure according to the metadata list (see photo in document)
- [x] #96
- [x] #97
- [x] Present the profile & examples to BGE use cases for feedback (~June 2025)
- [x] Iterate...
- [x] Finalise profile (by Nov 2025, hard deadline for grant deliverable)

**Comment by alexhambley** [comment]
Check with @elichad + Nick due to BGE+ proposal.

**Comment by elichad** [comment]
See detailed issue list here: https://github.com/eScienceLab/bge-ro-crate-profile/issues

**Comment by ianhinder** [comment]
@elichad is this still "Review required"?

**Comment by elichad** [comment]
Yes - still soliciting feedback from the BGE community. Presenting the work at a few events this month, which should help with this

**Comment by elichad** [comment]
A first draft is completed and can be found here: [repo](https://github.com/eScienceLab/bge-ro-crate-profile), [website](https://esciencelab.org.uk/bge-ro-crate-profile/).

There is still some work to do - see https://github.com/eScienceLab/bge-ro-crate-profile/issues , but for now this work is paused as the deliverable deadline has been met.
